wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1675224565.304805
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      2:
      - 1
      - 37
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.15
      5: 0.13.9
      8:
      - 5
beta:
  desc: null
  value: 0.6
burn_in:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.6
temperature:
  desc: null
  value: 2
use_soft_tgts:
  desc: null
  value: true
